version: '3.7'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: mysql
    ports:
      - 8082:80
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
    ports:
    - 8083:8081
  rebrow:
    image: marian/rebrow:latest
    environment:
      REDIS_HOSTS: redis
    ports:
    - 8084:5001
#  mongo:
#    image: mongo:4.1
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123
#    ports:
#      - 27017:27017
#  mongo-express:
#    image: mongo-express
#    volumes:
#      - ./volumes/mongodb:/data/db
#    ports:
#    - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
#      ME_CONFIG_MONGODB_SERVER: mongo
